[colors.primary]
background = "#282c34"
foreground = "#abb2bf"

# Normal colors
[colors.normal]
black   = "#181a1f"
red     = "#e86671"
green   = "#98c379"
yellow  = "#e5c07b"
blue    = "#61afef"
magenta = "#d19a66"
cyan    = "#56b6c2"
white   = "#f2e5bc"

[colors.bright]
black   = "#101012"
red     = "#e45649"
green   = "#50a14f"
yellow  = "#986801"
blue    = "#4078f2"
magenta = "#d19a66"
cyan    = "#0184bc"
white   = "#f2e5bc"


