[colors.primary]
background = "0x111111"
foreground = "0xd5c4a1"

# Normal colors
[colors.normal]
black   = "#32302f"
red     = "#cc6666"
green   = "#99cc99"
yellow  = "#8ec07c"
blue    = "#81a2be"
magenta = "#b294bb"
cyan    = "#8abeb7"
white   = "#f2e5bc"

# Bright colors (same as normal colors)
[colors.bright]
black   = "#32302f"
red     = "#cc6666"
green   = "#99cc99"
yellow  = "#8ec07c"
blue    = "#81a2be"
magenta = "#b294bb"
cyan    = "#8abeb7"
white   = "#f2e5bc"
